# Generated by Django 6.0.3 on 2026-05-24 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_options_user_email_verification_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='reset_code_expires',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='reset_password_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
