# Generated by Django 6.0.3 on 2026-05-19 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InternetPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('speed', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
                ('package_type', models.CharField(choices=[('HOME', 'Home Internet'), ('BUSINESS', 'Business Internet'), ('CORPORATE', 'Corporate Internet')], default='HOME', max_length=20)),
                ('features', models.JSONField(default=dict)),
                ('validity_days', models.IntegerField(default=30)),
                ('is_active', models.BooleanField(default=True)),
                ('is_popular', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'internet_packages',
                'ordering': ['price'],
            },
        ),
    ]
