# Generated by Django 6.0.3 on 2026-05-24 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='internetpackage',
            name='first_month_free',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='internetpackage',
            name='installation_fee',
            field=models.DecimalField(decimal_places=2, default=10000.0, max_digits=10),
        ),
    ]
